title: Shoko Docs
description: Online documentation for Shoko, an anime cataloging program.
url: https://docs.shokoanime.com/

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile', "README.md", "CNAME", "templates", "package.json", "package-lock.json", "node_modules", "gulpfile.js"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true
